#!/bin/bash

[ -n "$dbserver" ] && psql_options="${psql_options} -h ${dbserver}"
[ -n "$dbuser" ] && psql_options="${psql_options} -U ${dbuser}"

if [ "$1" == "config" ];then
cat << EOF
graph_title Postgres queries2 on all databases
graph_args --base 1000
graph_vlabel Queries per \${graph_period}
graph_category PostgreSQL
graph_info Shows number of select, insert, update and delete queries
sel_seq.label s_selects
sel_seq.info Sequential selects on all tables
sel_seq.type DERIVE
sel_seq.min 0
sel_seq_rows.label s_select rows
sel_seq_rows.info Rows returned from sequential selects
sel_seq_rows.type DERIVE
sel_seq.min 0
sel_idx.label i_selects
sel_idx.info Sequential selects on all indexes
sel_idx.type DERIVE
sel_seq.min 0
sel_idx_rows.label i_select rows
sel_idx_rows.info Rows returned form index selects
sel_idx_rows.type DERIVE
sel_seq_rows.min 0
inserts.label inserts
inserts.info Rows inserted on all tables
inserts.type DERIVE
inserts.min 0
updates.label updates
updates.info Rows updated on all tables
updates.type DERIVE
updates.min 0
deletes.label deletes
deletes.info Rows deleted from all tables
deletes.type DERIVE
deletes.min 0
EOF
else

all_databases=`psql ${psql_options} -Atl 2> /dev/null | egrep -v "^(postgres|template)" | cut -d'|' -f1`

for db in $all_databases; do
psql ${psql_options} -At $db << EOF
select SUM(seq_scan), SUM(seq_tup_read), SUM(idx_scan), SUM(idx_tup_fetch), SUM(n_tup_ins), SUM(n_tup_upd), SUM(n_tup_del)
	from pg_stat_all_tables;
EOF
done | awk -F'|' '
{ 
  sel_seq += $1 ;  
  sel_seq_rows += $2 ;
  sel_idx += $3 ;
  sel_idx_rows += $4 ;
  inserts += $5 ;
  updates += $6 ;
  deletes += $7
}
END { 
  printf "sel_seq.value %d\nsel_seq_rows.value %d\nsel_idx.value %d\nsel_idx_rows.value %d\ninserts.value %d\nupdates.value %d\ndeletes.value %d\n", sel_seq, sel_seq_rows, sel_idx, sel_idx_rows, inserts, updates, deletes
}'
	
#    my $sql = "SELECT SUM(seq_scan),SUM(seq_tup_read), ";
 #   $sql   .= "SUM(idx_scan),SUM(idx_tup_fetch), ";
 #   $sql   .= "SUM(n_tup_ins),SUM(n_tup_upd),SUM(n_tup_del) ";
 #   $sql   .= "from pg_stat_all_tables";
#	echo	1
fi

